# Generated by Django 5.1.1 on 2024-10-04 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_alter_comment_owner_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='user_id',
            new_name='user',
        ),
    ]
