# Generated by Django 5.1.1 on 2024-10-04 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0004_rename_product_id_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
